// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: queries.sql

package db

import (
	"context"
)

const createCategory = `-- name: CreateCategory :exec
insert into categories (id, name)
values (?,?)
`

type CreateCategoryParams struct {
	ID   int32
	Name string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, createCategory, arg.ID, arg.Name)
	return err
}

const createCourse = `-- name: CreateCourse :exec
insert into courses (id, name, category_id)
values (?,?,?)
`

type CreateCourseParams struct {
	ID         int32
	Name       string
	CategoryID int32
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) error {
	_, err := q.db.ExecContext(ctx, createCourse, arg.ID, arg.Name, arg.CategoryID)
	return err
}
